[build]
  command = "gridsome build"
  publish = "dist"
[build.environment]
  NODE_VERSION = "10"

[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

    [plugins.inputs.policies]
    defaultSrc = "'self'"
    fontSrc = "'self' data:"
    imgSrc = "'self' data: blob:"
    scriptSrc = "'report-sample' 'self' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://identity.netlify.com/ https://unpkg.com/ 'unsafe-eval'"
    styleSrc = "'report-sample' 'self' 'unsafe-hashes' 'unsafe-inline'"
    objectSrc = "'none'"
    baseUri = "'self'"
    connectSrc = "'self'"
    frameSrc = "'self' https://www.google.com  https://www.google.com/recaptcha/"
    workerSrc = "'none'"
    mediaSrc = "'self'"
    manifestSrc = "'self'"

