[build]
  command = "gridsome build"
  publish = "dist"
[build.environment]
  NODE_VERSION = "10"

[[headers]]
 for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' font-src 'self' data: ;"