backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "offers" # Used in routes, e.g., /admin/collections/blog
    label: "Offers" # Used in the UI
    folder: "content/offers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "md"
    fields: # The fields for each document, usually in front matter
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - {
          label: "Opublikowana",
          name: "published",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Zdjęcie",
          name: "cover_image",
          widget: "image",
          required: true,
        }
      - { label: "Opis", name: "description", widget: "markdown" }
      - { label: "Zawartość", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Us"
        file: "content/pages/about/index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown }
          - label: Business Profile
            name: profile
            widget: list
            fields:
              - { label: Body, name: body, widget: string }

      - name: "home"
        label: "Strona Główna"
        file: "content/pages/home/index.md"
        fields:
          - label: "Ekran powitalny"
            name: "welcomeScreen"
            widget: object,
            collapsed: true,
            fields:
              - { label: Tekst powitalny, name: welcomeText, widget: string }
              - {
                  label: Tekst w przycisku,
                  name: welcomeButton,
                  widget: string,
                }
          - { label: Nagłówek nad ofertami, name: offerTitle, widget: string }

  - name: "footer"
    label: "Footer"
    files:
      - name: "about"
        label: "About Us"
        file: "content/pages/footer/footer_about.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown }
      - name: "contact_details"
        label: "Contact Details"
        file: "content/pages/footer/footer_contact_details.md"
        fields:
          - { label: Title, name: title, widget: string }
          - label: Contact Type
            name: contacts
            widget: list
            fields:
              - { label: Contact, name: contact, widget: markdown }
