backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "offers" # Used in routes, e.g., /admin/collections/blog
    label: "Oferty" # Used in the UI
    folder: "content/offers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "md"
    fields: # The fields for each document, usually in front matter
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - {
          label: "Opublikowana",
          name: "published",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Zdjęcie",
          name: "cover_image",
          widget: "image",
          required: true,
        }
      - { label: "Opis", name: "description", widget: "markdown" }
      - { label: "Zawartość", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Strony"
    files:
      - name: "about"
        label: "O firmie"
        file: "content/pages/about/index.md"
        fields:
          - { label: Tytuł, name: title, widget: string }
          - { label: Tekst o firmie, name: content, widget: markdown }

      - name: home
        label: Strona Główna
        file: content/pages/home/index.md
        fields:
          - label: Ekran powitalny
            name: welcome_screen
            widget: object
            fields:
              - label: Tekst powitalny
                name: welcome_text
                widget: string

              - label: Teskt Przycisk
                name: welcome_button
                widget: string

              - label: Obraz tła
                name: welcome_image
                widget: image
                allow_multiple: false

          - label: Tytuł nad ofertami
            name: offer_title
            widget: string

      - name: contact
        label: Kontakt
        file: content/pages/contact/index.md
        fields:
          - label: Nagłówek nad danymi kontaktowymi
            name: contact_title
            widget: string

          - label: Tekst informacyjny
            name: contact_content
            widget: markdown

          - label: Nagłówek nad formularzem
            name: form_title
            widget: string

  - name: "footer"
    label: "Stopka"
    files:
      - name: "about"
        label: "O firmie"
        file: "content/pages/footer/footer_about.md"
        fields:
          - { label: Nagłówek, name: title, widget: string }
          - { label: Notka o firmie, name: content, widget: markdown }
      - name: "contact_details"
        label: "Lista kontaktów"
        file: "content/pages/footer/footer_contact_details.md"
        fields:
          - { label: Title, name: title, widget: string }
          - label: kontakt
            name: contacts
            widget: list
            fields:
              - { label: Nazwa, name: contact, widget: markdown }
