backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "offers" # Used in routes, e.g., /admin/collections/blog
    label: "Oferty" # Used in the UI
    media_folder: "/static/uploads"
    public_folder: "/uploads"
    folder: "content/offers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "md"
    fields: # The fields for each document, usually in front matter
      - { label: "Tytuł", name: "title", widget: "string" }
      - {
          label: "Opublikowana",
          name: "published",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Zdjęcie miniatury oferty",
          name: "card_image",
          widget: "image",
          required: true,
        }
      - {
          label: "Tło nagłówka oferty",
          name: "offer_image",
          widget: "image",
          required: true,
        }
      - { label: "Treść", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Strony"
    files:
      - name: about
        label: O firmie
        file: content/pages/about/index.md
        fields:
          - { label: "Tytuł", name: "title", widget: "string", required: true }
          - {
              label: "Zdjęcie w tle",
              name: "main_image",
              widget: "image",
              required: true,
            }
          - {
              label: "Opis nad zdjęciem",
              name: "description",
              widget: "markdown",
              required: true,
            }
          - {
              label: "Opis działalności",
              name: "body",
              widget: "markdown",
              required: true,
            }

      - name: home
        label: Strona Główna
        file: content/pages/home/index.md
        fields:
          - label: Ekran powitalny
            name: welcome_screen
            widget: object
            fields:
              - {
                  label: "Tekst powitalny",
                  name: "welcome_text",
                  widget: "string",
                  required: true,
                }
              - {
                  label: "Teskt w przycisku",
                  name: "welcome_button",
                  widget: "string",
                  required: true,
                }
              - {
                  label: "Obraz tła",
                  name: "main_image",
                  widget: "image",
                  allow_multiple: false,
                }
          - {
              label: "Tytuł nad ofertami",
              name: "offer_title",
              widget: "string",
              required: true,
            }
          - label: "Liczniki"
            name: "counters"
            widget: "list"
            fields:
              - {
                  label: Ikona nad licznikiem,
                  name: icon,
                  widget: material-icons,
                }
              - { label: Wartość licznika, name: value, widget: number }
              - { label: Tytuł licznika, name: title, widget: string }

      - name: contact
        label: Kontakt
        file: content/pages/contact/index.md
        fields:
          - {
              label: "Nagłówek nad danymi kontaktowymi",
              name: "contact_title",
              widget: "string",
              required: true,
            }

          - {
              label: "Nagłówek nad formularzem",
              name: "form_title",
              widget: "string",
              required: true,
            }

          - {
              label: "Tekst informacyjny",
              name: "body",
              widget: "markdown",
              required: true,
            }

      - name: notFound
        label: Nie Znaleziono
        file: content/pages/notFound/index.md
        fields:
          - {
              label: "Kod numeru błędu",
              name: "error_number",
              widget: "string",
              required: true,
            }
          - {
              label: "Treść nagłówka wyświetlonego pod numerem 404",
              name: "error_title",
              widget: "string",
              required: true,
            }
          - {
              label: "Treść przycisku służącego do przejścia na stronę główną",
              name: "home_button_title",
              widget: "string",
              required: true,
            }

          - {
              label: "Treść przycisku służącego do przejścia na stronę kontaktową",
              name: "contact_button_title",
              widget: "string",
              required: true,
            }

  - name: "footer"
    label: "Stopka"
    files:
      - name: "about"
        label: "O firmie"
        file: "content/pages/footer/footer_about.md"
        fields:
          - {
              label: "Notka o firmie",
              name: "body",
              widget: "markdown",
              required: true,
            }

      - name: "contact_details"
        label: "Lista kontaktów"
        file: "content/pages/footer/footer_contact_details.md"
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - label: "Kontakty"
            name: "contacts"
            widget: "list"
            fields:
              - {
                  label: "Nazwa",
                  name: "contact",
                  widget: "string",
                  required: true,
                }
